version: "3.0"
services:
  wg-access-server:
    # to build the docker image from the source
    build:
      dockerfile: Dockerfile
      context: .
    container_name: wg-access-server
    cap_add:
      - NET_ADMIN
    volumes:
      - "wg-access-server-data:/data"
    environment:
      - "WG_ADMIN_USERNAME=halo"
      - "WG_ADMIN_PASSWORD=$WG_ADMIN_PASSWORD"
      - "WG_WIREGUARD_PRIVATE_KEY=$WG_WIREGUARD_PRIVATE_KEY"
      - "WG_VPN_CIDR=10.69.200.0/24"
      - "WG_VPN_ALLOWED_IPS=10.0.0.0/8"
      - "WG_DNS_UPSTREAM=10.69.0.1"
    ports:
      - "8000:8000/tcp"
      - "51820:51820/udp"
    devices:
      - "/dev/net/tun:/dev/net/tun"

# shared volumes with the host
volumes:
  wg-access-server-data:
    driver: local
