volumes:
  etc_wireguard:

services:
  wg-easy:
    environment:
      - LANG=en
      - WG_HOST=13.236.203.94
      - PASSWORD_HASH=$$2a$12$$Zy4/XrIjCwioNHKMubrc9uNW5WONKnkU18vKm8koc/SUVoczuYzQS
      - PORT=51821
      - WG_PORT=51820
      - WG_DEFAULT_DNS=10.69.0.1
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_DEFAULT_ADDRESS=10.69.0.x
    # image: ghcr.io/wg-easy/wg-easy
    build:
      dockerfile: ./Dockerfile
    container_name: wg-easy
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
